# 资源已经打包到镜像里面
version: "3"
services:
  web-service:
    image: nnnnzs/nnnnzs-cn-web:latest
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    command: npm run start:docker
