# 资源还在本地，映射本地目录
version: "3"
services:
  web-service:
    container_name: nnnnzs-cn-web
    image: node:20.14.0
    working_dir: /usr/src/app
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
      - NODE_ENV=production
      - PORT=4000
      - HOST=0.0.0.0
    command: npm run start:docker
